In [1]:
porosity = [0.4,0.2,0.33,0.6,0.43,0.76]

In [2]:
porosity

[0.4, 0.2, 0.33, 0.6, 0.43, 0.76]

In [3]:
porosity.append(0.458) #append for adding element at the last of list

In [4]:
porosity

[0.4, 0.2, 0.33, 0.6, 0.43, 0.76, 0.458]

In [5]:
#insert = adding element at given index
a = [1,2,3,4,5,6,7]

c = 'Petroleum'

a.insert(4,c)

In [6]:
a

[1, 2, 3, 4, 'Petroleum', 5, 6, 7]

In [7]:
s = 'Porosity and Permeability'

In [8]:
s

'Porosity and Permeability'

In [9]:
s[2]

'r'

In [10]:
s[-2]

't'

In [16]:
s[::-1]

'ytilibaemreP dna ytisoroP'

In [19]:
## List Operatioms 

In [20]:
porosity_A = [0.1,0.2,0.3]
porosity_B = [0.4,0.5,0.6]

In [21]:
porosity_A+porosity_B

[0.1, 0.2, 0.3, 0.4, 0.5, 0.6]

In [22]:
porosity_A*3

[0.1, 0.2, 0.3, 0.1, 0.2, 0.3, 0.1, 0.2, 0.3]

In [23]:
porosity_A*porosity_B

TypeError: can't multiply sequence by non-int of type 'list'

In [24]:
import numpy as np 

In [28]:
ar_A  = np.array(porosity_A)
ar_B = np.array(porosity_B)

In [29]:
ar_A

array([0.1, 0.2, 0.3])

In [30]:
ar_B

array([0.4, 0.5, 0.6])

In [31]:
ar_A+ar_B

array([0.5, 0.7, 0.9])

In [32]:
ar_A*ar_B

array([0.04, 0.1 , 0.18])

# Range 

In [33]:
#Generator function of python 

In [34]:
range(10)

range(0, 10)

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Syntax = > range(starting,stopping,step size)

In [37]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
list(range(20,1,-1))

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]

#Write Even Numbers from 0 to 100

 -> list(range(0,101,2))
 
 -> list(range(0,100,2))
 
 -> list(range(0,102,2))



In [39]:
list(range(0,101,2))

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [40]:
list(range(0,102,2))

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [41]:
a = int(input('Lower Bound for my list: '))
b = int(input('Upper Bound for my list: '))
c = int(input('Step size: '))

list(range(a,b,c))

Lower Bound for my list: 10
Upper Bound for my list: 50
Step size: 5


[10, 15, 20, 25, 30, 35, 40, 45]

# Tuples: 

-> ()

-> Immutable : Cannot  change elements,because of this passwords can be saved in tuples

-> Ordered

-> Databases returns tuples (Mongo DB, etc) 

In [42]:
oilprd = (5000,1000,4322,5633,7892)

In [43]:
type(oilprd)

tuple

In [44]:
oilprd[1]

1000

In [45]:
oilprd[1] = 200

TypeError: 'tuple' object does not support item assignment

In [46]:
oilprd_list = list(oilprd)

In [47]:
oilprd_list

[5000, 1000, 4322, 5633, 7892]

In [48]:
oilprd

(5000, 1000, 4322, 5633, 7892)

In [49]:
type(oilprd_list)

list

In [50]:
oilprd_list[1] = 200

In [51]:
oilprd_list

[5000, 200, 4322, 5633, 7892]

In [52]:
oilprd_new_tuple = tuple(oilprd_list)

In [53]:
oilprd_new_tuple

(5000, 200, 4322, 5633, 7892)

In [54]:
a = (45,65,"porosity",[4,5,6,'hj',('Perm',567,43,23)])

In [55]:
a

(45, 65, 'porosity', [4, 5, 6, 'hj', ('Perm', 567, 43, 23)])

In [56]:
a[-1]

[4, 5, 6, 'hj', ('Perm', 567, 43, 23)]

In [57]:
a[-1][-1]

('Perm', 567, 43, 23)

In [58]:
a[-1][-1][0]

'Perm'

In [59]:
a[3]

[4, 5, 6, 'hj', ('Perm', 567, 43, 23)]

In [61]:
a[3][4][0]

'Perm'

## Sets = unordered collection of data

    - No duplication 
    - {}
    - Unique data, characters: use sets 
    - Faster than list 

In [62]:
words = {'are','am','is','hello','perm','are','am','is',"porosity","hello"}

In [63]:
words

{'am', 'are', 'hello', 'is', 'perm', 'porosity'}

In [64]:
words[3]

TypeError: 'set' object is not subscriptable

In [67]:
perm = {23,12,32,23,1221,2324,23,1,21,43,43,32,23,'petroleum','is'}

In [68]:
perm 

{1, 12, 1221, 21, 23, 2324, 32, 43, 'is', 'petroleum'}

# Dictionary

    1. keys:value pair of data 
    2. useful in mongo db 
    3. Numeric values of key is allowed
    4. Can store lists,dict,tuple,set
    5. Helps us to store data with labels 
    
    - {} => Key:value pairs

In [69]:
d = {}

In [70]:
type(d)

dict

In [71]:
d = {2,3,'3343',3}

In [72]:
d

{2, 3, '3343'}

In [73]:
type(d)

set

In [74]:
d = {'name':"jaiyesh"}

In [75]:
d

{'name': 'jaiyesh'}

In [76]:
rock_properties = {'porosity':0.25,"permeability":150,'lithology':'Limestone'}

In [77]:
rock_properties

{'porosity': 0.25, 'permeability': 150, 'lithology': 'Limestone'}

In [78]:
type(rock_properties)

dict

##### Keys must be unique 

In [79]:
rock_prop = {'lithology':'Sandstone','poro':0.25,'lithology':'Shale'}

In [80]:
rock_prop

{'lithology': 'Shale', 'poro': 0.25}

In [81]:
d1 = {32:'petroleum',"name":'jaiyesh'}

In [82]:
d1

{32: 'petroleum', 'name': 'jaiyesh'}

In [83]:
## Special characters for key = _,@<# ?

In [85]:
d1 = {"_3223":'jc'}

In [86]:
d1

{'_3223': 'jc'}

In [87]:
#values can be anything: Lists, tuples,sets, dictionarie

In [88]:
rocks = {'Rock_Number':[1,2,3,4],'porosities':(0.2,0.4,0.5,0.7),'lithology':{'Rock_Number_1':'Shale','Rock_Number_2':'SST',
                                                                            'Rock_Number_3':'LMT','Rock_Number_4':'LMT'}}

In [89]:
rocks

{'Rock_Number': [1, 2, 3, 4],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'}}

In [90]:
## Accessing data

In [91]:
rocks[0]

KeyError: 0

In [94]:
rocks['porosities'][3]

0.7

In [96]:
rocks.keys()

dict_keys(['Rock_Number', 'porosities', 'lithology'])

In [97]:
rocks['lithology']

{'Rock_Number_1': 'Shale',
 'Rock_Number_2': 'SST',
 'Rock_Number_3': 'LMT',
 'Rock_Number_4': 'LMT'}

In [98]:
rocks['lithology'].keys()

dict_keys(['Rock_Number_1', 'Rock_Number_2', 'Rock_Number_3', 'Rock_Number_4'])

In [99]:
rocks['lithology']['Rock_Number_3']

'LMT'

In [100]:
rocks['porosities']

(0.2, 0.4, 0.5, 0.7)

In [101]:
rocks

{'Rock_Number': [1, 2, 3, 4],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'}}

In [102]:
type(rocks)

dict

In [105]:
rocks['Rock_Number']

[1, 2, 3, 4]

In [106]:
type(rocks['Rock_Number'])

list

In [108]:
rocks['Rock_Number'][1:3]

[2, 3]

In [109]:
rocks['porosities']

(0.2, 0.4, 0.5, 0.7)

In [110]:
rocks

{'Rock_Number': [1, 2, 3, 4],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'}}

In [111]:
#Muttable, can add new key valkue pairs
rocks['Water_Saturation'] = {0.2,0.4,0.3,0.6}

In [112]:
rocks

{'Rock_Number': [1, 2, 3, 4],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'},
 'Water_Saturation': {0.2, 0.3, 0.4, 0.6}}

In [114]:
rocks['Water_Saturation'][2]

TypeError: 'set' object is not subscriptable

In [120]:
rocks['Rock_Number'][2] = 'new'

In [121]:
rocks

{'Rock_Number': [1, 2, 'new', 4],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'},
 'Water_Saturation': {0.2, 0.3, 0.4, 0.6}}

In [123]:
rocks['Rock_Number'] = ['RN1 ','RN 2','RN 3','RN 4']

In [124]:
rocks

{'Rock_Number': ['RN1 ', 'RN 2', 'RN 3', 'RN 4'],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'},
 'Water_Saturation': {0.2, 0.3, 0.4, 0.6}}

In [125]:
d1 = {'_3443':'jc','name':'Jaiyesh','n':[2,3,4,5,67,8,'js',(1,2,3,4)],'t':(3,4,5,6),'d':{1:23,'jv':'hs'}}

In [126]:
d1

{'_3443': 'jc',
 'name': 'Jaiyesh',
 'n': [2, 3, 4, 5, 67, 8, 'js', (1, 2, 3, 4)],
 't': (3, 4, 5, 6),
 'd': {1: 23, 'jv': 'hs'}}

In [128]:
d1['d']['jv']

'hs'

In [129]:
# Remove

In [130]:
rocks

{'Rock_Number': ['RN1 ', 'RN 2', 'RN 3', 'RN 4'],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'},
 'Water_Saturation': {0.2, 0.3, 0.4, 0.6}}

In [132]:
rocks.pop('Water_Saturation')

{0.2, 0.3, 0.4, 0.6}

In [133]:
rocks

{'Rock_Number': ['RN1 ', 'RN 2', 'RN 3', 'RN 4'],
 'porosities': (0.2, 0.4, 0.5, 0.7),
 'lithology': {'Rock_Number_1': 'Shale',
  'Rock_Number_2': 'SST',
  'Rock_Number_3': 'LMT',
  'Rock_Number_4': 'LMT'}}

In [134]:
rock_properties


{'porosity': 0.25, 'permeability': 150, 'lithology': 'Limestone'}

In [135]:
rock_prop

{'lithology': 'Shale', 'poro': 0.25}

In [136]:
import pandas as pd

In [139]:
pd.DataFrame(rock_properties,index =[1])

porosity  permeability  lithology
1      0.25           150  Limestone

## Summary of Data Structures:

    1. Lists: Mutable, EMpty lists are used heavily to populate it later during the code, ordered
    2. Tuples: Immutable, data cannot be changed, ordered
    3. Sets: Uniqueness of elements and unordered
    4. Dictionaries: Key:Value, mutable